#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_SummaryData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RealPrice")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertMainData(MainData instance);
    partial void UpdateMainData(MainData instance);
    partial void DeleteMainData(MainData instance);
    partial void InsertSummaryData(SummaryData instance);
    partial void UpdateSummaryData(SummaryData instance);
    partial void DeleteSummaryData(SummaryData instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PR_SummaryData.Properties.Settings.Default.RealPriceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MainData> MainData
		{
			get
			{
				return this.GetTable<MainData>();
			}
		}
		
		public System.Data.Linq.Table<SummaryData> SummaryData
		{
			get
			{
				return this.GetTable<SummaryData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MainData")]
	public partial class MainData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _City;
		
		private string _SellType;
		
		private string _DISTRICT;
		
		private string _CASE_T;
		
		private string _LOCATION;
		
		private System.Nullable<decimal> _LANDA;
		
		private string _CASE_F;
		
		private string _LANDA_X;
		
		private string _LANDA_Y;
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _SCNT;
		
		private string _SBUILD;
		
		private string _TBUILD;
		
		private string _BUITYPE;
		
		private string _PBUILD;
		
		private string _MBUILD;
		
		private System.Nullable<System.DateTime> _FDATE;
		
		private System.Nullable<decimal> _FAREA;
		
		private System.Nullable<int> _BUILD_R;
		
		private System.Nullable<int> _BUILD_L;
		
		private System.Nullable<int> _BUILD_B;
		
		private string _BUILD_P;
		
		private string _RULE;
		
		private System.Nullable<long> _TPRICE;
		
		private System.Nullable<decimal> _UPRICE;
		
		private string _PARKTYPE;
		
		private System.Nullable<decimal> _PAREA;
		
		private System.Nullable<int> _PPRICE;
		
		private string _RMNOTE;
		
		private string _ID2;
		
		private System.Nullable<bool> _isActive;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnSellTypeChanging(string value);
    partial void OnSellTypeChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnCASE_TChanging(string value);
    partial void OnCASE_TChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnLANDAChanging(System.Nullable<decimal> value);
    partial void OnLANDAChanged();
    partial void OnCASE_FChanging(string value);
    partial void OnCASE_FChanged();
    partial void OnLANDA_XChanging(string value);
    partial void OnLANDA_XChanged();
    partial void OnLANDA_YChanging(string value);
    partial void OnLANDA_YChanged();
    partial void OnSDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSDATEChanged();
    partial void OnSCNTChanging(string value);
    partial void OnSCNTChanged();
    partial void OnSBUILDChanging(string value);
    partial void OnSBUILDChanged();
    partial void OnTBUILDChanging(string value);
    partial void OnTBUILDChanged();
    partial void OnBUITYPEChanging(string value);
    partial void OnBUITYPEChanged();
    partial void OnPBUILDChanging(string value);
    partial void OnPBUILDChanged();
    partial void OnMBUILDChanging(string value);
    partial void OnMBUILDChanged();
    partial void OnFDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnFDATEChanged();
    partial void OnFAREAChanging(System.Nullable<decimal> value);
    partial void OnFAREAChanged();
    partial void OnBUILD_RChanging(System.Nullable<int> value);
    partial void OnBUILD_RChanged();
    partial void OnBUILD_LChanging(System.Nullable<int> value);
    partial void OnBUILD_LChanged();
    partial void OnBUILD_BChanging(System.Nullable<int> value);
    partial void OnBUILD_BChanged();
    partial void OnBUILD_PChanging(string value);
    partial void OnBUILD_PChanged();
    partial void OnRULEChanging(string value);
    partial void OnRULEChanged();
    partial void OnTPRICEChanging(System.Nullable<long> value);
    partial void OnTPRICEChanged();
    partial void OnUPRICEChanging(System.Nullable<decimal> value);
    partial void OnUPRICEChanged();
    partial void OnPARKTYPEChanging(string value);
    partial void OnPARKTYPEChanged();
    partial void OnPAREAChanging(System.Nullable<decimal> value);
    partial void OnPAREAChanged();
    partial void OnPPRICEChanging(System.Nullable<int> value);
    partial void OnPPRICEChanged();
    partial void OnRMNOTEChanging(string value);
    partial void OnRMNOTEChanged();
    partial void OnID2Changing(string value);
    partial void OnID2Changed();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    #endregion
		
		public MainData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SellType
		{
			get
			{
				return this._SellType;
			}
			set
			{
				if ((this._SellType != value))
				{
					this.OnSellTypeChanging(value);
					this.SendPropertyChanging();
					this._SellType = value;
					this.SendPropertyChanged("SellType");
					this.OnSellTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASE_T", DbType="NVarChar(50)")]
		public string CASE_T
		{
			get
			{
				return this._CASE_T;
			}
			set
			{
				if ((this._CASE_T != value))
				{
					this.OnCASE_TChanging(value);
					this.SendPropertyChanging();
					this._CASE_T = value;
					this.SendPropertyChanged("CASE_T");
					this.OnCASE_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="NVarChar(400)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDA", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> LANDA
		{
			get
			{
				return this._LANDA;
			}
			set
			{
				if ((this._LANDA != value))
				{
					this.OnLANDAChanging(value);
					this.SendPropertyChanging();
					this._LANDA = value;
					this.SendPropertyChanged("LANDA");
					this.OnLANDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASE_F", DbType="NVarChar(50)")]
		public string CASE_F
		{
			get
			{
				return this._CASE_F;
			}
			set
			{
				if ((this._CASE_F != value))
				{
					this.OnCASE_FChanging(value);
					this.SendPropertyChanging();
					this._CASE_F = value;
					this.SendPropertyChanged("CASE_F");
					this.OnCASE_FChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDA_X", DbType="NVarChar(50)")]
		public string LANDA_X
		{
			get
			{
				return this._LANDA_X;
			}
			set
			{
				if ((this._LANDA_X != value))
				{
					this.OnLANDA_XChanging(value);
					this.SendPropertyChanging();
					this._LANDA_X = value;
					this.SendPropertyChanged("LANDA_X");
					this.OnLANDA_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDA_Y", DbType="NVarChar(50)")]
		public string LANDA_Y
		{
			get
			{
				return this._LANDA_Y;
			}
			set
			{
				if ((this._LANDA_Y != value))
				{
					this.OnLANDA_YChanging(value);
					this.SendPropertyChanging();
					this._LANDA_Y = value;
					this.SendPropertyChanged("LANDA_Y");
					this.OnLANDA_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this.OnSDATEChanging(value);
					this.SendPropertyChanging();
					this._SDATE = value;
					this.SendPropertyChanged("SDATE");
					this.OnSDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCNT", DbType="NVarChar(200)")]
		public string SCNT
		{
			get
			{
				return this._SCNT;
			}
			set
			{
				if ((this._SCNT != value))
				{
					this.OnSCNTChanging(value);
					this.SendPropertyChanging();
					this._SCNT = value;
					this.SendPropertyChanged("SCNT");
					this.OnSCNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBUILD", DbType="NVarChar(200)")]
		public string SBUILD
		{
			get
			{
				return this._SBUILD;
			}
			set
			{
				if ((this._SBUILD != value))
				{
					this.OnSBUILDChanging(value);
					this.SendPropertyChanging();
					this._SBUILD = value;
					this.SendPropertyChanged("SBUILD");
					this.OnSBUILDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBUILD", DbType="NVarChar(50)")]
		public string TBUILD
		{
			get
			{
				return this._TBUILD;
			}
			set
			{
				if ((this._TBUILD != value))
				{
					this.OnTBUILDChanging(value);
					this.SendPropertyChanging();
					this._TBUILD = value;
					this.SendPropertyChanged("TBUILD");
					this.OnTBUILDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUITYPE", DbType="NVarChar(200)")]
		public string BUITYPE
		{
			get
			{
				return this._BUITYPE;
			}
			set
			{
				if ((this._BUITYPE != value))
				{
					this.OnBUITYPEChanging(value);
					this.SendPropertyChanging();
					this._BUITYPE = value;
					this.SendPropertyChanged("BUITYPE");
					this.OnBUITYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBUILD", DbType="NVarChar(50)")]
		public string PBUILD
		{
			get
			{
				return this._PBUILD;
			}
			set
			{
				if ((this._PBUILD != value))
				{
					this.OnPBUILDChanging(value);
					this.SendPropertyChanging();
					this._PBUILD = value;
					this.SendPropertyChanged("PBUILD");
					this.OnPBUILDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBUILD", DbType="NVarChar(300)")]
		public string MBUILD
		{
			get
			{
				return this._MBUILD;
			}
			set
			{
				if ((this._MBUILD != value))
				{
					this.OnMBUILDChanging(value);
					this.SendPropertyChanging();
					this._MBUILD = value;
					this.SendPropertyChanged("MBUILD");
					this.OnMBUILDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDATE", DbType="Date")]
		public System.Nullable<System.DateTime> FDATE
		{
			get
			{
				return this._FDATE;
			}
			set
			{
				if ((this._FDATE != value))
				{
					this.OnFDATEChanging(value);
					this.SendPropertyChanging();
					this._FDATE = value;
					this.SendPropertyChanged("FDATE");
					this.OnFDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAREA", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> FAREA
		{
			get
			{
				return this._FAREA;
			}
			set
			{
				if ((this._FAREA != value))
				{
					this.OnFAREAChanging(value);
					this.SendPropertyChanging();
					this._FAREA = value;
					this.SendPropertyChanged("FAREA");
					this.OnFAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILD_R", DbType="Int")]
		public System.Nullable<int> BUILD_R
		{
			get
			{
				return this._BUILD_R;
			}
			set
			{
				if ((this._BUILD_R != value))
				{
					this.OnBUILD_RChanging(value);
					this.SendPropertyChanging();
					this._BUILD_R = value;
					this.SendPropertyChanged("BUILD_R");
					this.OnBUILD_RChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILD_L", DbType="Int")]
		public System.Nullable<int> BUILD_L
		{
			get
			{
				return this._BUILD_L;
			}
			set
			{
				if ((this._BUILD_L != value))
				{
					this.OnBUILD_LChanging(value);
					this.SendPropertyChanging();
					this._BUILD_L = value;
					this.SendPropertyChanged("BUILD_L");
					this.OnBUILD_LChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILD_B", DbType="Int")]
		public System.Nullable<int> BUILD_B
		{
			get
			{
				return this._BUILD_B;
			}
			set
			{
				if ((this._BUILD_B != value))
				{
					this.OnBUILD_BChanging(value);
					this.SendPropertyChanging();
					this._BUILD_B = value;
					this.SendPropertyChanged("BUILD_B");
					this.OnBUILD_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILD_P", DbType="NVarChar(50)")]
		public string BUILD_P
		{
			get
			{
				return this._BUILD_P;
			}
			set
			{
				if ((this._BUILD_P != value))
				{
					this.OnBUILD_PChanging(value);
					this.SendPropertyChanging();
					this._BUILD_P = value;
					this.SendPropertyChanged("BUILD_P");
					this.OnBUILD_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[RULE]", Storage="_RULE", DbType="NVarChar(50)")]
		public string RULE
		{
			get
			{
				return this._RULE;
			}
			set
			{
				if ((this._RULE != value))
				{
					this.OnRULEChanging(value);
					this.SendPropertyChanging();
					this._RULE = value;
					this.SendPropertyChanged("RULE");
					this.OnRULEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TPRICE", DbType="BigInt")]
		public System.Nullable<long> TPRICE
		{
			get
			{
				return this._TPRICE;
			}
			set
			{
				if ((this._TPRICE != value))
				{
					this.OnTPRICEChanging(value);
					this.SendPropertyChanging();
					this._TPRICE = value;
					this.SendPropertyChanged("TPRICE");
					this.OnTPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPRICE", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> UPRICE
		{
			get
			{
				return this._UPRICE;
			}
			set
			{
				if ((this._UPRICE != value))
				{
					this.OnUPRICEChanging(value);
					this.SendPropertyChanging();
					this._UPRICE = value;
					this.SendPropertyChanged("UPRICE");
					this.OnUPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARKTYPE", DbType="NVarChar(50)")]
		public string PARKTYPE
		{
			get
			{
				return this._PARKTYPE;
			}
			set
			{
				if ((this._PARKTYPE != value))
				{
					this.OnPARKTYPEChanging(value);
					this.SendPropertyChanging();
					this._PARKTYPE = value;
					this.SendPropertyChanged("PARKTYPE");
					this.OnPARKTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAREA", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> PAREA
		{
			get
			{
				return this._PAREA;
			}
			set
			{
				if ((this._PAREA != value))
				{
					this.OnPAREAChanging(value);
					this.SendPropertyChanging();
					this._PAREA = value;
					this.SendPropertyChanged("PAREA");
					this.OnPAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPRICE", DbType="Int")]
		public System.Nullable<int> PPRICE
		{
			get
			{
				return this._PPRICE;
			}
			set
			{
				if ((this._PPRICE != value))
				{
					this.OnPPRICEChanging(value);
					this.SendPropertyChanging();
					this._PPRICE = value;
					this.SendPropertyChanged("PPRICE");
					this.OnPPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMNOTE", DbType="NVarChar(400)")]
		public string RMNOTE
		{
			get
			{
				return this._RMNOTE;
			}
			set
			{
				if ((this._RMNOTE != value))
				{
					this.OnRMNOTEChanging(value);
					this.SendPropertyChanging();
					this._RMNOTE = value;
					this.SendPropertyChanged("RMNOTE");
					this.OnRMNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID2", DbType="NVarChar(400)")]
		public string ID2
		{
			get
			{
				return this._ID2;
			}
			set
			{
				if ((this._ID2 != value))
				{
					this.OnID2Changing(value);
					this.SendPropertyChanging();
					this._ID2 = value;
					this.SendPropertyChanged("ID2");
					this.OnID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SummaryData")]
	public partial class SummaryData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _City;
		
		private string _SellType;
		
		private string _DISTRICT;
		
		private string _CASE_T;
		
		private string _LOCATION;
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private double _Avg;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnSellTypeChanging(string value);
    partial void OnSellTypeChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnCASE_TChanging(string value);
    partial void OnCASE_TChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnSDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSDATEChanged();
    partial void OnAvgChanging(double value);
    partial void OnAvgChanged();
    #endregion
		
		public SummaryData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SellType
		{
			get
			{
				return this._SellType;
			}
			set
			{
				if ((this._SellType != value))
				{
					this.OnSellTypeChanging(value);
					this.SendPropertyChanging();
					this._SellType = value;
					this.SendPropertyChanged("SellType");
					this.OnSellTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASE_T", DbType="NVarChar(50)")]
		public string CASE_T
		{
			get
			{
				return this._CASE_T;
			}
			set
			{
				if ((this._CASE_T != value))
				{
					this.OnCASE_TChanging(value);
					this.SendPropertyChanging();
					this._CASE_T = value;
					this.SendPropertyChanged("CASE_T");
					this.OnCASE_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="NVarChar(400)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this.OnSDATEChanging(value);
					this.SendPropertyChanging();
					this._SDATE = value;
					this.SendPropertyChanged("SDATE");
					this.OnSDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avg", DbType="Float NOT NULL")]
		public double Avg
		{
			get
			{
				return this._Avg;
			}
			set
			{
				if ((this._Avg != value))
				{
					this.OnAvgChanging(value);
					this.SendPropertyChanging();
					this._Avg = value;
					this.SendPropertyChanged("Avg");
					this.OnAvgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
